# DakuWorks Secrets Template
#
# WARNING: Do NOT commit actual secrets to Git!
# This is a TEMPLATE showing the required secret structure.
#
# To create the actual secret, run:
# kubectl create secret generic dakuworks-secrets -n dakuworks-dev \
#   --from-literal=database-user='dakuworks' \
#   --from-literal=database-password='YOUR_SECURE_PASSWORD' \
#   --from-literal=jwt-secret='YOUR_JWT_SECRET' \
#   --from-literal=email-user='your-email@gmail.com' \
#   --from-literal=email-password='YOUR_EMAIL_APP_PASSWORD'

apiVersion: v1
kind: Secret
metadata:
  name: dakuworks-secrets
  namespace: dakuworks-dev
  labels:
    app: dakuworks
    managed-by: manual
  annotations:
    description: "Application secrets - must be created manually before deployment"
type: Opaque
stringData:
  # PostgreSQL credentials
  database-user: "REPLACE_WITH_DB_USER"
  database-password: "REPLACE_WITH_SECURE_PASSWORD"

  # JWT secret for authentication
  jwt-secret: "REPLACE_WITH_RANDOM_JWT_SECRET"

  # Email service credentials (for notifications)
  email-user: "REPLACE_WITH_EMAIL_ADDRESS"
  email-password: "REPLACE_WITH_EMAIL_APP_PASSWORD"

---
# Example commands to generate secure values:
#
# Generate random database password:
# openssl rand -base64 32
#
# Generate JWT secret:
# openssl rand -base64 64
#
# For Gmail SMTP:
# 1. Enable 2FA on your Google account
# 2. Create an App Password: https://myaccount.google.com/apppasswords
# 3. Use the app password (not your regular password)
